"""empty message

Revision ID: 07a483b9c69f
Revises: 
Create Date: 2026-04-07 08:37:38.647730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '07a483b9c69f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'login',
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        )
    )

    op.execute("UPDATE \"user\" SET login = 'User_' || CAST(id AS VARCHAR)")

    op.alter_column('user', 'login', nullable=False)

    op.alter_column('user', 'nickname',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
