"""empty message

Revision ID: 34135f4167d7
Revises: 8a09a72a2a72
Create Date: 2026-04-13 06:11:23.444021

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34135f4167d7'
down_revision = '8a09a72a2a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rolepermission',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('roleuserserver',
    sa.Column('user_server_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_server_id'], ['userserver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_server_id', 'role_id')
    )
    op.add_column('server', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'server', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('userserver', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('userserver_user_id_server_id_key'), 'userserver', type_='unique')
    op.create_unique_constraint(None, 'userserver', ['user_id', 'server_id', 'order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userserver', type_='unique')
    op.create_unique_constraint(op.f('userserver_user_id_server_id_key'), 'userserver', ['user_id', 'server_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('userserver', 'order')
    op.drop_constraint(None, 'server', type_='foreignkey')
    op.drop_column('server', 'owner_id')
    op.drop_table('roleuserserver')
    op.drop_table('rolepermission')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
