"""empty message

Revision ID: ad1fa1616edb
Revises: 911d292d0fd0
Create Date: 2026-04-18 05:02:16.821793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ad1fa1616edb'
down_revision = '911d292d0fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'channel', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_column('channel', 'category_id')
    # ### end Alembic commands ###
