"""empty message

Revision ID: d2298925201d
Revises: 34135f4167d7
Create Date: 2026-04-14 03:57:40.596305

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd2298925201d'
down_revision = '34135f4167d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'created_at')
    # ### end Alembic commands ###
